export default {
  LIST_INTERACTIONS: 'LIST_INTERACTIONS',
  LIST_INTERACTIONS_DONE: 'LIST_INTERACTIONS_DONE',
  SHOW_INTERACTION: 'SHOW_INTERACTION',
  SHOW_INTERACTION_DONE: 'SHOW_INTERACTION_DONE',
}
